"""movie desc., rating, runtime

Revision ID: 2c7ef181f58b
Revises: 75ab701ec650
Create Date: 2019-12-23 19:15:50.653039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c7ef181f58b'
down_revision = '75ab701ec650'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('runtime', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.drop_column('runtime')
        batch_op.drop_column('rating')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
