"""render_as_batch changed, delete column

Revision ID: 36144cd94d5f
Revises: 7ed16e16918c
Create Date: 2019-12-23 14:53:39.397627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36144cd94d5f'
down_revision = '7ed16e16918c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_column('test')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
