"""test

Revision ID: 480c35dc538d
Revises: 154fe7f52080
Create Date: 2019-12-23 16:18:06.004666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '480c35dc538d'
down_revision = '154fe7f52080'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.alter_column('seat_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('show_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('row', schema=None) as batch_op:
        batch_op.alter_column('auditorium_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('seat', schema=None) as batch_op:
        batch_op.alter_column('auditorium_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('row_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('show', schema=None) as batch_op:
        batch_op.alter_column('auditorium_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('movie_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('show', schema=None) as batch_op:
        batch_op.alter_column('movie_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('auditorium_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('seat', schema=None) as batch_op:
        batch_op.alter_column('row_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('auditorium_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('row', schema=None) as batch_op:
        batch_op.alter_column('auditorium_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('show_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('seat_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
