"""empty message

Revision ID: 75ab701ec650
Revises: 1fc1701173d6
Create Date: 2019-12-23 19:12:04.415624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75ab701ec650'
down_revision = '1fc1701173d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.alter_column('auditorium_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.alter_column('auditorium_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
