"""change res aud nullable

Revision ID: a1ae4bc2639d
Revises: 480c35dc538d
Create Date: 2019-12-23 17:56:59.311567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1ae4bc2639d'
down_revision = '480c35dc538d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.alter_column('auditorium_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.alter_column('auditorium_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
