"""movie rating, duration

Revision ID: ca07415df213
Revises: 36144cd94d5f
Create Date: 2019-12-23 16:07:44.515843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca07415df213'
down_revision = '36144cd94d5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('rating', sa.String(), nullable=False))
        batch_op.alter_column('director_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.alter_column('auditorium_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('seat_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('show_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('row', schema=None) as batch_op:
        batch_op.alter_column('auditorium_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('seat', schema=None) as batch_op:
        batch_op.alter_column('auditorium_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('row_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('show', schema=None) as batch_op:
        batch_op.alter_column('auditorium_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('movie_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('show', schema=None) as batch_op:
        batch_op.alter_column('movie_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('auditorium_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('seat', schema=None) as batch_op:
        batch_op.alter_column('row_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('auditorium_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('row', schema=None) as batch_op:
        batch_op.alter_column('auditorium_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('show_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('seat_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('auditorium_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.alter_column('director_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('rating')
        batch_op.drop_column('duration')

    # ### end Alembic commands ###
