"""add movie_id to reservation

Revision ID: ed14e7a75cd8
Revises: a1ae4bc2639d
Create Date: 2019-12-23 18:21:03.960527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed14e7a75cd8'
down_revision = 'a1ae4bc2639d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('movie_id', sa.Integer(), nullable=True))
        batch_op.alter_column('auditorium_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'movie', ['movie_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('auditorium_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('movie_id')

    # ### end Alembic commands ###
